import { SiteContent } from "./types";

export const DEFAULT_SITE_CONTENTS: SiteContent[] = [
  // -------------------------------------------------------------
  // HERO SECTION
  // -------------------------------------------------------------
  {
    key: "hero_badge",
    value: "🌾 ОХУ - Монгол Улс | Үр Тариа, Малын Тэжээлийн Бөөний Худалдаа",
    section: "HERO",
    label: "Hero дэд тодотгол (Badge)",
    field_type: "text",
    updated_at: new Date().toISOString(),
  },
  {
    key: "hero_title",
    value: "Их Хэмжээний Үр Тариа, Малын Тэжээлийн Бөөний Худалдаа",
    section: "HERO",
    label: "Hero үндсэн гарчиг (Title)",
    field_type: "text",
    updated_at: new Date().toISOString(),
  },
  {
    key: "hero_subtitle",
    value: "ОХУ-ын Алтай хязгаар, Сибирийн шилдэг үйлдвэр, элеваторуудаас хүнсний улаан буудай, малын тэжээлийн хивэг, шар буурцагны шротыг үйлдвэрийн бөөний үнээр Монголын зах зээлд шууд нийлүүлнэ.",
    section: "HERO",
    label: "Hero дэд тайлбар (Subtitle)",
    field_type: "textarea",
    updated_at: new Date().toISOString(),
  },
  {
    key: "hero_cta_primary",
    value: "Бөөний захиалга өгөх",
    section: "HERO",
    label: "Hero үндсэн товчны бичвэр (Primary CTA)",
    field_type: "text",
    updated_at: new Date().toISOString(),
  },
  {
    key: "hero_cta_secondary",
    value: "Бүтээгдэхүүний жагсаалт & Үнэ",
    section: "HERO",
    label: "Hero 2-р товчны бичвэр (Secondary CTA)",
    field_type: "text",
    updated_at: new Date().toISOString(),
  },
  {
    key: "hero_stat1_value",
    value: "150,000+ тн",
    section: "HERO",
    label: "Үзүүлэлт 1: Гарчиг / Тоо (Жилийн нийлүүлэлт)",
    field_type: "text",
    updated_at: new Date().toISOString(),
  },
  {
    key: "hero_stat1_label",
    value: "Жилийн бөөний нийлүүлэлт",
    section: "HERO",
    label: "Үзүүлэлт 1: Дэд тайлбар",
    field_type: "text",
    updated_at: new Date().toISOString(),
  },
  {
    key: "hero_stat2_value",
    value: "Шууд Үйлдвэрээс",
    section: "HERO",
    label: "Үзүүлэлт 2: Гарчиг / Утга (Бөөний жишиг үнэ)",
    field_type: "text",
    updated_at: new Date().toISOString(),
  },
  {
    key: "hero_stat2_label",
    value: "Бөөний жишиг үнэ",
    section: "HERO",
    label: "Үзүүлэлт 2: Дэд тайлбар",
    field_type: "text",
    updated_at: new Date().toISOString(),
  },
  {
    key: "hero_stat3_value",
    value: "SGS / МХЕГ",
    section: "HERO",
    label: "Үзүүлэлт 3: Гарчиг / Утга (Баталгаат лаборатори)",
    field_type: "text",
    updated_at: new Date().toISOString(),
  },
  {
    key: "hero_stat3_label",
    value: "100% Лаборатори баталгаа",
    section: "HERO",
    label: "Үзүүлэлт 3: Дэд тайлбар",
    field_type: "text",
    updated_at: new Date().toISOString(),
  },
  {
    key: "hero_stat4_value",
    value: "Толгойт & Дархан",
    section: "HERO",
    label: "Үзүүлэлт 4: Гарчиг / Байршил (Толгойт & Дархан)",
    field_type: "text",
    updated_at: new Date().toISOString(),
  },
  {
    key: "hero_stat4_label",
    value: "Өөрийн элеватор бааз",
    section: "HERO",
    label: "Үзүүлэлт 4: Дэд тайлбар (Өөрийн элеватор бааз)",
    field_type: "text",
    updated_at: new Date().toISOString(),
  },

  // -------------------------------------------------------------
  // ABOUT SECTION
  // -------------------------------------------------------------
  {
    key: "about_badge",
    value: "Бидний тухай & Давуу тал",
    section: "ABOUT",
    label: "Бидний тухай шошго (Badge)",
    field_type: "text",
    updated_at: new Date().toISOString(),
  },
  {
    key: "about_title",
    value: "Монголын Хүнс, Хөдөө Аж Ахуйн Салбарын Бөөний Түнш",
    section: "ABOUT",
    label: "Бидний тухай гарчиг (Title)",
    field_type: "text",
    updated_at: new Date().toISOString(),
  },
  {
    key: "about_description",
    value: "PTS Agro Trade нь гурилын үйлдвэрүүд, эрчимжсэн мал аж ахуй, тэжээлийн үйлдвэрүүдэд ОХУ-ын Алтай, Новосибирскийн элеваторуудаас стандартын шаардлага хангасан үр тариа, уургийн тэжээлийг шууд үйлдвэрийн бөөний үнээр нийлүүлж байна.",
    section: "ABOUT",
    label: "Компанийн ерөнхий танилцуулга",
    field_type: "textarea",
    updated_at: new Date().toISOString(),
  },
  {
    key: "about_feat1_title",
    value: "ОХУ-ын Үйлдвэрүүдтэй Шууд Гэрээ",
    section: "ABOUT",
    label: "Давуу тал 1: Гарчиг",
    field_type: "text",
    updated_at: new Date().toISOString(),
  },
  {
    key: "about_feat1_desc",
    value: "Алтай хязгаар, Новосибирскийн томоохон элеватор, үйлдвэрүүдтэй зуучлагчгүй шууд нийлүүлэлтийн гэрээтэй.",
    section: "ABOUT",
    label: "Давуу тал 1: Тайлбар",
    field_type: "textarea",
    updated_at: new Date().toISOString(),
  },
  {
    key: "about_feat2_title",
    value: "Өөрийн Зориулалтын Элеватор & Бааз",
    section: "ABOUT",
    label: "Давуу тал 2: Гарчиг",
    field_type: "text",
    updated_at: new Date().toISOString(),
  },
  {
    key: "about_feat2_desc",
    value: "Толгойт өртөө болон Дархан хотод төмөр замын салаа зам бүхий 40,000 тн үр тариа хадгалах элеватортой.",
    section: "ABOUT",
    label: "Давуу тал 2: Тайлбар",
    field_type: "textarea",
    updated_at: new Date().toISOString(),
  },
  {
    key: "about_feat3_title",
    value: "100% Лабораторийн Баталгаажилт",
    section: "ABOUT",
    label: "Давуу тал 3: Гарчиг",
    field_type: "text",
    updated_at: new Date().toISOString(),
  },
  {
    key: "about_feat3_desc",
    value: "Ачаа бүр дээр SGS болон Улсын Мэргэжлийн Хяналтын итгэмжлэгдсэн сорилтын протокол дагалдана.",
    section: "ABOUT",
    label: "Давуу тал 3: Тайлбар",
    field_type: "textarea",
    updated_at: new Date().toISOString(),
  },
  {
    key: "about_feat4_title",
    value: "Гаалийн Ногоон Гарц & Түргэн Бэлтгэл",
    section: "ABOUT",
    label: "Давуу тал 4: Гарчиг",
    field_type: "text",
    updated_at: new Date().toISOString(),
  },
  {
    key: "about_feat4_desc",
    value: "Хил, гааль, ургамал хорио цээрийн бүрдүүлэлтийг мэргэшсэн брокерууд 24 цагийн дотор шийдвэрлэнэ.",
    section: "ABOUT",
    label: "Давуу тал 4: Тайлбар",
    field_type: "textarea",
    updated_at: new Date().toISOString(),
  },

  // -------------------------------------------------------------
  // LOGISTICS SECTION
  // -------------------------------------------------------------
  {
    key: "logistics_badge",
    value: "Хүргэлтийн нөхцөл",
    section: "LOGISTICS",
    label: "Хүргэлтийн шошго (Badge)",
    field_type: "text",
    updated_at: new Date().toISOString(),
  },
  {
    key: "logistics_title",
    value: "Бөөний нийлүүлэлтийн хүргэлтийн сонголтууд",
    section: "LOGISTICS",
    label: "Хүргэлтийн хэсгийн гарчиг",
    field_type: "text",
    updated_at: new Date().toISOString(),
  },
  {
    key: "logistics_subtitle",
    value: "Бөөний захиалгын хэмжээ болон очих цэгээс хамааран үйлдвэр, фермийн агуулахад авто замаар шууд буулгах эсвэл төмөр замын чингэлэгээр нийлүүлнэ.",
    section: "LOGISTICS",
    label: "Хүргэлтийн ерөнхий тайлбар",
    field_type: "textarea",
    updated_at: new Date().toISOString(),
  },
  // Хэлбэр А (Авто тээвэр)
  {
    key: "logistics_route_a_badge",
    value: "Хэлбэр А: Авто замын шууд хүргэлт",
    section: "LOGISTICS",
    label: "Хэлбэр А: Шошго (Badge)",
    field_type: "text",
    updated_at: new Date().toISOString(),
  },
  {
    key: "logistics_route_a_time",
    value: "24 - 48 цагт",
    section: "LOGISTICS",
    label: "Хэлбэр А: Тээвэрлэлтийн хугацаа",
    field_type: "text",
    updated_at: new Date().toISOString(),
  },
  {
    key: "logistics_route_a_title",
    value: "Авто Тээврээр Шууд Хүргэх",
    section: "LOGISTICS",
    label: "Хэлбэр А (Авто зам): Үндсэн гарчиг",
    field_type: "text",
    updated_at: new Date().toISOString(),
  },
  {
    key: "logistics_route_a_subtitle",
    value: "Боомтоос зам дагуух аймаг, сум, фермүүдэд шууд буулгах",
    section: "LOGISTICS",
    label: "Хэлбэр А: Дэд тайлбар",
    field_type: "text",
    updated_at: new Date().toISOString(),
  },
  {
    key: "logistics_route_a_route",
    value: "Алтанбулаг / Сүхбаатар → Дархан → Зүүнхараа → Улаанбаатар",
    section: "LOGISTICS",
    label: "Хэлбэр А: Маршрутын өртөө, чиглэл (→ эсвэл -> ашиглана)",
    field_type: "text",
    updated_at: new Date().toISOString(),
  },
  {
    key: "logistics_route_a_capacity",
    value: "25-50 тн тусгай тэвштэй болон битүү ачааны автомашинууд.",
    section: "LOGISTICS",
    label: "Хэлбэр А: Даацын тайлбар",
    field_type: "text",
    updated_at: new Date().toISOString(),
  },
  {
    key: "logistics_route_a_advantage",
    value: "Хил гарснаас 24-48 цагт зам дагуу байрлах фермүүдэд шууд буулгах боломжтой.",
    section: "LOGISTICS",
    label: "Хэлбэр А: Давуу тал",
    field_type: "text",
    updated_at: new Date().toISOString(),
  },
  {
    key: "logistics_route_a_recommended",
    value: "20-100 тонн",
    section: "LOGISTICS",
    label: "Хэлбэр А: Зөвлөмж хэмжээ",
    field_type: "text",
    updated_at: new Date().toISOString(),
  },
  // Хэлбэр Б (Төмөр зам)
  {
    key: "logistics_route_b_badge",
    value: "Хэлбэр Б: Төмөр замын вагон нийлүүлэлт",
    section: "LOGISTICS",
    label: "Хэлбэр Б: Шошго (Badge)",
    field_type: "text",
    updated_at: new Date().toISOString(),
  },
  {
    key: "logistics_route_b_time",
    value: "4 - 7 хоног",
    section: "LOGISTICS",
    label: "Хэлбэр Б: Тээвэрлэлтийн хугацаа",
    field_type: "text",
    updated_at: new Date().toISOString(),
  },
  {
    key: "logistics_route_b_title",
    value: "Төмөр замын вагон & чингэлэг нийлүүлэлт",
    section: "LOGISTICS",
    label: "Хэлбэр Б (Төмөр зам): Үндсэн гарчиг",
    field_type: "text",
    updated_at: new Date().toISOString(),
  },
  {
    key: "logistics_route_b_subtitle",
    value: "Улаанбаатар терминал болон зүүн бүсийн өртөөнүүдэд бөөнөөр буулгах",
    section: "LOGISTICS",
    label: "Хэлбэр Б: Дэд тайлбар",
    field_type: "text",
    updated_at: new Date().toISOString(),
  },
  {
    key: "logistics_route_b_route",
    value: "Наушки / ОХУ → Сүхбаатар өртөө → УБ (Толгойт/Амгалан) → Зүүн аймгууд",
    section: "LOGISTICS",
    label: "Хэлбэр Б: Маршрутын өртөө, чиглэл (→ эсвэл -> ашиглана)",
    field_type: "text",
    updated_at: new Date().toISOString(),
  },
  {
    key: "logistics_route_b_capacity",
    value: "60-70 тн даацын битүү чингэлэг.",
    section: "LOGISTICS",
    label: "Хэлбэр Б: Даацын тайлбар",
    field_type: "text",
    updated_at: new Date().toISOString(),
  },
  {
    key: "logistics_route_b_advantage",
    value: "Их хэмжээний ачаанд тээврийн өртөг хямд, цаг агаарын эрсдэлгүй.",
    section: "LOGISTICS",
    label: "Хэлбэр Б: Давуу тал",
    field_type: "text",
    updated_at: new Date().toISOString(),
  },
  {
    key: "logistics_route_b_recommended",
    value: "50-70 тонн",
    section: "LOGISTICS",
    label: "Хэлбэр Б: Зөвлөмж хэмжээ",
    field_type: "text",
    updated_at: new Date().toISOString(),
  },

  // -------------------------------------------------------------
  // CONTACT & BRANCH SECTION
  // -------------------------------------------------------------
  {
    key: "contact_badge",
    value: "Шуурхай холбоо барих & Захиалга",
    section: "CONTACT",
    label: "Холбоо барих шошго (Badge)",
    field_type: "text",
    updated_at: new Date().toISOString(),
  },
  {
    key: "contact_title",
    value: "Бөөний Захиалга Өгөх & Төв Баазын Байршил",
    section: "CONTACT",
    label: "Захиалгын хэсгийн гарчиг",
    field_type: "text",
    updated_at: new Date().toISOString(),
  },
  {
    key: "contact_subtitle",
    value: "Бөөний нийлүүлэлтийн захиалгын маягтыг бөглөхөд манай худалдааны менежер шуурхай холбогдож, гэрээ болон нийлүүлэлтийг баталгаажуулна.",
    section: "CONTACT",
    label: "Захиалгын хэсгийн дэд тайлбар",
    field_type: "textarea",
    updated_at: new Date().toISOString(),
  },
  {
    key: "contact_phone",
    value: "7711-8899",
    section: "CONTACT",
    label: "Үндсэн утасны дугаар",
    field_type: "text",
    updated_at: new Date().toISOString(),
  },
  {
    key: "contact_viber",
    value: "+976 9911-8421",
    section: "CONTACT",
    label: "Viber дугаар",
    field_type: "text",
    updated_at: new Date().toISOString(),
  },
  {
    key: "contact_facebook_url",
    value: "https://facebook.com/ptsagrotrade",
    section: "CONTACT",
    label: "Facebook хуудасны бүтэн холбоос (URL)",
    field_type: "text",
    updated_at: new Date().toISOString(),
  },
  {
    key: "contact_facebook_handle",
    value: "fb.com/ptsagrotrade",
    section: "CONTACT",
    label: "Facebook хуудасны богино линк / харагдах бичвэр (Жишээ: fb.com/...)",
    field_type: "text",
    updated_at: new Date().toISOString(),
  },
  {
    key: "contact_email",
    value: "order@pts-logistics.mn",
    section: "CONTACT",
    label: "Холбоо барих мэйл",
    field_type: "text",
    updated_at: new Date().toISOString(),
  },
  {
    key: "contact_branch_title",
    value: "Төв Бааз & Байршлын Хаяг",
    section: "CONTACT",
    label: "Хаягийн картын гарчиг",
    field_type: "text",
    updated_at: new Date().toISOString(),
  },
  {
    key: "contact_address_label",
    value: "Бөөний төв / Баазын хаяг:",
    section: "CONTACT",
    label: "Хаягийн дэд гарчиг/нэр",
    field_type: "text",
    updated_at: new Date().toISOString(),
  },
  {
    key: "contact_address",
    value: "Улаанбаатар хот, Сонгинохайрхан дүүрэг, 20-р хороо, Толгойт өртөө, PTS Бааз",
    section: "CONTACT",
    label: "Төв баазын хаяг",
    field_type: "textarea",
    updated_at: new Date().toISOString(),
  },
  {
    key: "contact_map_badge",
    value: "Төв бааз, Агуулах",
    section: "CONTACT",
    label: "Газрын зургийн дээрх шошго",
    field_type: "text",
    updated_at: new Date().toISOString(),
  },
  {
    key: "contact_hours",
    value: "Даваа - Баасан: 09:00 - 18:00 (Бямба: 10:00 - 15:00)",
    section: "CONTACT",
    label: "Ажиллах цагийн хуваарь",
    field_type: "text",
    updated_at: new Date().toISOString(),
  },
  {
    key: "contact_google_maps_url",
    value: "https://maps.google.com/?q=Tolgoit+Station+Ulaanbaatar",
    section: "CONTACT",
    label: "Google Maps шууд холбоос (URL)",
    field_type: "text",
    updated_at: new Date().toISOString(),
  },

  // -------------------------------------------------------------
  // COMMON & FOOTER
  // -------------------------------------------------------------
  {
    key: "site_brand_name",
    value: "PTS AGRO TRADE",
    section: "COMMON",
    label: "Сайтын брэндийн нэр",
    field_type: "text",
    updated_at: new Date().toISOString(),
  },
  {
    key: "site_brand_subtitle",
    value: "Үр тариа, тэжээлийн бөөний худалдаа",
    section: "COMMON",
    label: "Брэндийн дэд тайлбар / Уриа",
    field_type: "text",
    updated_at: new Date().toISOString(),
  },
  {
    key: "footer_description",
    value: "ОХУ, Сибирээс их хэмжээний үр тариа, малын тэжээлийг Монголын гурил, тэжээлийн үйлдвэр, фермүүдэд найдвартай нийлүүлэгч B2B бөөний худалдааны платформ.",
    section: "COMMON",
    label: "Хөл хэсгийн компанийн тайлбар",
    field_type: "textarea",
    updated_at: new Date().toISOString(),
  },
  {
    key: "footer_copyright",
    value: "© 2026 PTS Agro Trade (ПромТрейдСервис ХХК). Бүх эрх хуулиар хамгаалагдсан.",
    section: "COMMON",
    label: "Зохиогчийн эрх (Copyright)",
    field_type: "text",
    updated_at: new Date().toISOString(),
  },
  {
    key: "orders_board_title",
    value: "Бөөний Нийлүүлэлт & Түгээлтийн Явц",
    section: "COMMON",
    label: "Нийлүүлэлтийн самбарын үндсэн гарчиг",
    field_type: "text",
    updated_at: new Date().toISOString(),
  },
  {
    key: "orders_board_subtitle",
    value: "Харилцагч үйлдвэр, аж ахуй нэгжүүдийн төв бааз болон ОХУ-аас ачигдсан бөөний захиалгуудын явц.",
    section: "COMMON",
    label: "Нийлүүлэлтийн самбарын дэд тайлбар",
    field_type: "textarea",
    updated_at: new Date().toISOString(),
  },
  {
    key: "products_title",
    value: "Бүтээгдэхүүний Бөөний Үнэ & Шинжилгээ",
    section: "COMMON",
    label: "Бүтээгдэхүүний хэсгийн үндсэн гарчиг",
    field_type: "text",
    updated_at: new Date().toISOString(),
  },
  {
    key: "products_subtitle",
    value: "Хүнсний буудай, малын тэжээл, уургийн шротын үйлдвэрийн бөөний үнэ, лабораторийн сорилтын протокол.",
    section: "COMMON",
    label: "Бүтээгдэхүүний хэсгийн дэд тайлбар",
    field_type: "textarea",
    updated_at: new Date().toISOString(),
  },
];
